PROGRAM ADDPKVARS
    USE PKVAR_MODULE
    IMPLICIT NONE
    TYPE(PKVAR) :: X, Y

    X = PKVAR(1D2, 1D1)
    Y = PKVAR(56D0, 34D-2)

    WRITE(*,*) "VECTOR 1: ", X
    WRITE(*,*) "VECTOR 2: ", Y

END PROGRAM ADDPKVARS